### PR TITLE
Removed "o" character

### PR DESCRIPTION
**Pull request by Machy8**

### CODE REVIEW

**Comment by pepa-linha** [comment]
Thanks ;-)

**Comment by Machy8** [comment]
You are welcome. 
But there is another thing. On line **570** there is `margin-bottom: 1px solid #f5f5f5;`. I was not sure if it should be **border-bottom**?

**Comment by pepa-linha** [comment]
Yes, fixed 👍  (uf, opraveno po takové době...)

**Comment by Machy8** [comment]
👍

**Pull request merged**
